name: Trigger Auto PR on push to update branch
on:
  push:
    branches:
      - update
  workflow_dispatch:

env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.TEMPLATES_CLI_TOKEN }}

jobs:
  run-reusable-autopr:
    uses: platformsh-templates/ghrw-templates/.github/workflows/autopr.yaml@main
    secrets: inherit
