name: Update last.updated
on:
  push:
    branches:
      - main
      - master

#env:
#  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
#  GH_TOKEN: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}

jobs:
  run-reusable-last-update:
    uses: platformsh-templates/ghrw-templates/.github/workflows/last-updated.yaml@main
    secrets: inherit
