name: Trigger Source Operations on a Schedule
on:
  schedule:
    # Run at 00:15 every day
    - cron: '15 */19 * * *'
  workflow_dispatch:

jobs:
  run-reusable-sop-update:
    uses: platformsh-templates/ghrw-templates/.github/workflows/sourceops.yaml@main
    secrets: inherit
