name: "TestPullRequestEnv"
run-name: "TestPullRequestEnv"
on:
  workflow_run:
    workflows: [ "platformsh" ]
    types:
      - completed
  pull_request:
    branches:
      - master
      - main

jobs:
  call-reusable-testpr:
    uses: platformsh-templates/ghrw-templates/.github/workflows/testprenvironment.yaml@main
    secrets: inherit

