name: "TestPrEnvironment"
on:
  workflow_run:
    workflows: [ "platformsh" ]
    types:
      - completed
  pull_request:
    branches:
      - master
      - main
env:
  BASELINE_URL: ${{ vars.BASELINE_URL }}
  GITHUB_TOKEN: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
jobs:
  test-pr-env:
    name: TestPrEnvironment
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' }}
    steps:
      - name: 'Check for Baseline URL'
        id: check-baseline-url
        run: |
          baseline=${{ vars.BASELINE_URL }}
          if [[ -z ${baseline} ]]; then
            echo "::warning::The url to use for generating baseline images must be set as a repository variable"
            exit 1;
          fi

      - name: 'Wait for psh and get target url'
        id: get-target-url
        uses: platformsh/gha-retrieve-psh-prenv-url@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Visual Regression Testing'
        id: test-environment
        uses: gilzow/gha-vrt@feat/import-scenarios
        with:
          baseline_url: ${{ vars.BASELINE_URL }}
          test_url: ${{ steps.get-target-url.outputs.target_url }}

      - name: 'VRT results?'
        id: vrt-results
        run: |
          vrt_results=${{ steps.test-environment.outputs.results }}
          echo "::notice::The results from the VRT test is ${vrt_results}"
          if [[ "false" == "${vrt_results}" ]]; then
            echo "::error::Visual Regression Test failed. See attached artifact."
            exit 1
          else
            echo "::notice::Visual Regression Test passed. Carry on, my wayward son."
          fi

