name: "TestPrEnvironment"
on:
  workflow_run:
    workflows: [ "platformsh" ]
    types:
      - completed
  pull_request:
    branches:
      - master
      - main
env:
  # @todo I dont think this is needed anymore
  GITHUB_TOKEN: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
jobs:
  call-reusable-testpr:
    uses: platformsh/ghrw-templates/.github/workflows/testprenvironment.yaml@ec9f682f757f30b40bb1105fa440e013efd632c0
    secrets: inherit

